### ISSUE TITLE
Unproper file path to /opt

### ISSUE THREAD

**Issue by novahs** [industrial-edge/device-kit-ntp-service#8]
## Summary

By convention, /opt is not the correct place to write the cache file. In some embedded system this folder can also be read-only.

## Version of the used components

Which versions of the Industrial Edge components did you use?

IEDK v1.8

## Steps to reproduce

/opt is read-only directory.

## What is the current bug behavior?

Service error:
![image](https://user-images.githubusercontent.com/119834937/206610468-efd59855-b398-426c-bdf8-fec60add6a8a.png)

## What is the expected correct behavior?

Should write to /etc instead.

**Comment by novahs** [comment]
PR submitted: https://github.com/industrial-edge/device-kit-ntp-service/pull/7

**Comment by kayvaz** [comment]
@novahs Thank you for your contribution. We will investigate the issue.

**Comment by saffetturkoglu** [comment]
@novahs 
I'm writing to inform you that we had reviewed your issue and solution and we greatly thanks the work you have done. We have decided to include your solution in our next release, which is currently in progress.

We will keep you updated on the progress of the release.

Best Regards

**Comment by saffetturkoglu** [comment]
The bug has been fixed in version 1.6.0-1
